---
- name: Deploy to Azure Web Apps
  hosts: all
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Authenticate with Azure
      shell: |
        az login --service-principal -u {{ lookup('env', 'AZURE_CLIENT_ID') }} -p {{ lookup('env', 'AZURE_SECRET') }} --tenant {{ lookup('env', 'AZURE_TENANT') }}
      register: azure_auth

    - name: Deploy artifact to web app
      shell: |
        az webapp deployment source config-zip --resource-group {{ resource_group }} --name {{ app_name }} --src ${{jarfile}}
      args:
        warn: false
